import DashboardLayout from "@/components/DashboardLayout";
import { EmptyState, PageHeader, TagPill } from "@/components/clinic/Ui";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { formatDate } from "@/lib/clinic";
import { CalendarDays, Search, Star } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

export default function SearchRecords() {
  const [, setLocation] = useLocation();
  const [patient, setPatient] = useState(""); const [medicine, setMedicine] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const input = useMemo(() => ({ patient: patient.trim() || undefined, medicine: medicine.trim() || undefined, from: from ? new Date(`${from}T00:00:00`) : undefined, to: to ? new Date(`${to}T23:59:59`) : undefined }), [patient, medicine, from, to]);
  const records = trpc.clinic.prescriptions.search.useQuery(input);
  const clear = () => { setPatient(""); setMedicine(""); setFrom(""); setTo(""); };
  return <DashboardLayout><div className="mx-auto max-w-7xl"><PageHeader eyebrow="Phase 2 · Search" title="Find prescription records" description="Search deterministic saved fields: patient name, phone number, medicine name, or prescription date." /><Card className="mt-7 border-0 bg-white shadow-[0_12px_32px_rgba(15,70,70,0.06)]"><CardContent className="p-5"><div className="grid gap-3 lg:grid-cols-[1.25fr_1fr_0.75fr_0.75fr_auto]"><div className="relative"><Search className="pointer-events-none absolute left-3.5 top-3 h-4 w-4 text-slate-400" /><Input value={patient} onChange={event => setPatient(event.target.value)} className="rounded-xl bg-slate-50 pl-9" placeholder="Patient name or phone" /></div><Input value={medicine} onChange={event => setMedicine(event.target.value)} className="rounded-xl bg-slate-50" placeholder="Medicine name" /><Input type="date" value={from} onChange={event => setFrom(event.target.value)} className="rounded-xl bg-slate-50" aria-label="From date" /><Input type="date" value={to} onChange={event => setTo(event.target.value)} className="rounded-xl bg-slate-50" aria-label="To date" /><Button variant="ghost" className="text-slate-500" onClick={clear}>Clear</Button></div></CardContent></Card><section className="mt-5"><Card className="border-0 bg-white shadow-[0_12px_32px_rgba(15,70,70,0.06)]"><CardContent className="p-0">{records.isLoading ? <div className="space-y-3 p-6">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-20 animate-pulse rounded-xl bg-slate-100" />)}</div> : records.data?.length ? records.data.map(record => <button key={record.id} onClick={() => setLocation(`/prescriptions/${record.id}`)} className="flex w-full items-center gap-4 border-b border-slate-100 px-5 py-4 text-left transition-colors last:border-0 hover:bg-teal-50/40 sm:px-6"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-slate-100">{record.imageUrl && <img src={record.imageUrl} alt="Prescription" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-bold text-slate-800">{record.patientName}</p>{record.important && <Star className="h-4 w-4 fill-amber-400 text-amber-400" />}</div><p className="mt-1 text-xs text-slate-400">{record.medicines?.map(item => item.name).filter(Boolean).slice(0, 3).join(" · ") || "No medicine list"}</p></div><div className="hidden gap-1 md:flex">{(record.tags ?? []).slice(0, 2).map(tag => <TagPill key={tag}>{tag}</TagPill>)}</div><span className="flex shrink-0 items-center gap-1.5 text-xs text-slate-400"><CalendarDays className="h-3.5 w-3.5" />{formatDate(record.createdAt)}</span></button>) : <div className="p-6"><EmptyState title="No matching records" description="Try a different patient, phone number, medicine name, or date range. Only saved, doctor-reviewed records are searched." /></div>}</CardContent></Card></section></div></DashboardLayout>;
}
